/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/textures/iOB.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Bank(props) {
  const { nodes, materials } = useGLTF("../../../textures/iOB.glb");
  return (
    <group scale={0.05} {...props} dispose={null}>
      <mesh
        geometry={nodes.Bank_Asset_Bank_TXTR_0.geometry}
        material={materials["Bank_TXTR.001"]}
      />
    </group>
  );
}

useGLTF.preload("../../../textures/iOB.glb");
